name: Discourse Telegram Mention Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Report PHP version
        run: php -v
      - name: Cache Last Post Id File
        uses: actions/cache@v2
        with:
          path: last_post_id.txt
          key: last_post_id
      - name: Run Discourse bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: php discourse_telegram_mention_bot.php
